import '../models/court.dart';
import '../models/court_availability.dart';
import '../config/app_config.dart';
import 'api_service.dart';

class CourtService {
  final ApiService _apiService = ApiService();

                                                                                                                                                                                                                                Future<List<Court>> getCourts() async {
                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                    final response = await _apiService.get(AppConfig.courts);
                                                                                                                                                                                                                                    final responseData = _apiService.handleResponse(response);

                                                                                                                                                                                                                                    // Handle different response formats
                                                                                                                                                                                                                                    List<dynamic> courtsList;
                                                                                                                                                                                                                                    if (responseData is List) {
                                                                                                                                                                                                                                      courtsList = responseData as List<dynamic>;
                                                                                                                                                                                                                                    } else if (responseData is Map && responseData.containsKey('data') && responseData['data'] is List) {
                                                                                                                                                                                                                                      courtsList = responseData['data'] as List<dynamic>;
                                                                                                                                                                                                                                    } else if (responseData is Map && responseData.containsKey('courts') && responseData['courts'] is List) {
                                                                                                                                                                                                                                      courtsList = responseData['courts'] as List<dynamic>;
                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                      throw Exception('Unexpected response format: $responseData');
                                                                                                                                                                                                                                    }

      final courts = courtsList.map((json) => Court.fromJson(json)).toList();
      
      return courts;
    } catch (e) {
      throw Exception('Error fetching courts: $e');
    }
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                Future<Court> getCourtById(String id) async {
                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                    final response = await _apiService.get('${AppConfig.courts}/$id');
                                                                                                                                                                                                                                    final responseData = _apiService.handleResponse(response);

                                                                                                                                                                                                                                    return Court.fromJson(responseData);
                                                                                                                                                                                                                                  } catch (e) {
                                                                                                                                                                                                                                    throw Exception('Error fetching court: $e');
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                Future<List<Court>> getAvailableCourts(DateTime date) async {
                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                    final response = await _apiService.get(
                                                                                                                                                                                                                                      '${AppConfig.courtAvailability}?date=${date.toIso8601String()}',
                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                    final responseData = _apiService.handleResponse(response);

                                                                                                                                                                                                                                    // Handle different response formats
                                                                                                                                                                                                                                    List<dynamic> courtsList;
                                                                                                                                                                                                                                    if (responseData is List) {
                                                                                                                                                                                                                                      courtsList = responseData as List<dynamic>;
                                                                                                                                                                                                                                    } else if (responseData is Map && responseData.containsKey('data') && responseData['data'] is List) {
                                                                                                                                                                                                                                      courtsList = responseData['data'] as List<dynamic>;
                                                                                                                                                                                                                                    } else if (responseData is Map && responseData.containsKey('courts') && responseData['courts'] is List) {
                                                                                                                                                                                                                                      courtsList = responseData['courts'] as List<dynamic>;
                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                      throw Exception('Unexpected response format: $responseData');
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                    return courtsList.map((json) => Court.fromJson(json)).toList();
                                                                                                                                                                                                                                  } catch (e) {
                                                                                                                                                                                                                                    throw Exception('Error fetching available courts: $e');
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                // Belirli bir kort için müsaitlik durumunu getir
                                                                                                                                                                                                                                Future<CourtAvailability> getCourtAvailability(String courtId, DateTime date) async {
                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                    final response = await _apiService.get(
                                                                                                                                                                                                                                      '${AppConfig.courts}/$courtId/availability?date=${date.toIso8601String()}',
                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                    final responseData = _apiService.handleResponse(response);

                                                                                                                                                                                                                                    return CourtAvailability.fromJson(responseData);
                                                                                                                                                                                                                                  } catch (e) {
                                                                                                                                                                                                                                    throw Exception('Error fetching court availability: $e');
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                // Belirli bir kort için rezerve edilmiş saatleri getir
                                                                                                                                                                                                                                Future<List<Map<String, dynamic>>> getCourtReservedSlots(String courtId, DateTime date) async {
                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                    final response = await _apiService.get(
                                                                                                                                                                                                                                      '${AppConfig.courts}/$courtId/reserved-slots?date=${date.toIso8601String()}',
                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                    final responseData = _apiService.handleResponse(response);

                                                                                                                                                                                                                                    // Handle different response formats
                                                                                                                                                                                                                                    List<dynamic> slotsList;
                                                                                                                                                                                                                                    if (responseData is List) {
                                                                                                                                                                                                                                      slotsList = responseData as List<dynamic>;
                                                                                                                                                                                                                                    } else if (responseData is Map && responseData.containsKey('data') && responseData['data'] is List) {
                                                                                                                                                                                                                                      slotsList = responseData['data'] as List<dynamic>;
                                                                                                                                                                                                                                    } else if (responseData is Map && responseData.containsKey('reservedSlots') && responseData['reservedSlots'] is List) {
                                                                                                                                                                                                                                      slotsList = responseData['reservedSlots'] as List<dynamic>;
                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                      throw Exception('Unexpected response format: $responseData');
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                    return slotsList.cast<Map<String, dynamic>>();
                                                                                                                                                                                                                                  } catch (e) {
                                                                                                                                                                                                                                    throw Exception('Error fetching court reserved slots: $e');
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                              }